codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "60...90"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "lib/l10n/generated/**/*"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "test/**/*"
  - "integration_test/**/*"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
